# Generated by Django 2.1.2 on 2018-12-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='difficulty',
            field=models.FloatField(),
        ),
    ]
