# Generated by Django 2.1.2 on 2018-12-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0002_auto_20181202_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='commitment',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='output',
            name='commitment',
            field=models.CharField(max_length=256),
        ),
    ]
