# Generated by Django 2.1.3 on 2018-12-04 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0004_remove_input_incubation'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='chainwork',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='difficulty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='subsidy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='input',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='explorer.Block'),
        ),
        migrations.AlterField(
            model_name='kernel',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kernels', to='explorer.Block'),
        ),
        migrations.AlterField(
            model_name='output',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='explorer.Block'),
        ),
    ]
