# Generated by Django 2.1.3 on 2018-12-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0006_auto_20181211_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='kernel',
            name='excess',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kernel',
            name='kernel_id',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kernel',
            name='maxHeight',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kernel',
            name='minHeight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
