# Generated by Django 2.1.5 on 2019-02-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0007_auto_20181227_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forks_event_detection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(db_index=True, max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='prev',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='block',
            name='height',
            field=models.IntegerField(db_index=True),
        ),
    ]
