# Generated by Django 2.1.5 on 2019-05-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0008_auto_20190228_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='height',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
