# Generated by Django 2.1.5 on 2019-07-10 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0009_auto_20190506_1353'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='output',
            unique_together=set(),
        ),
    ]
