# Generated by Django 2.1.5 on 2019-07-10 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0010_auto_20190710_1826'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='input',
            unique_together=set(),
        ),
    ]
