# Generated by Django 2.1.5 on 2019-08-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0011_auto_20190711_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forks_event_detection',
            name='height',
            field=models.IntegerField(),
        ),
    ]
