# Generated by Django 2.1.5 on 2020-05-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0012_auto_20190808_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='input',
            old_name='maturity',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='kernel',
            old_name='excess',
            new_name='extra',
        ),
        migrations.RemoveField(
            model_name='output',
            name='coinbase',
        ),
        migrations.RemoveField(
            model_name='output',
            name='incubation',
        ),
        migrations.AddField(
            model_name='input',
            name='extra',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='output',
            name='extra',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='input',
            name='commitment',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='output',
            name='commitment',
            field=models.CharField(max_length=128),
        ),
    ]
