# Generated by Django 2.1.5 on 2020-06-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0013_auto_20200518_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='output',
            name='maturity',
        ),
    ]
