# Generated by Django 2.1.5 on 2020-06-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0014_auto_20200612_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rollback_reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_from', models.PositiveIntegerField()),
                ('height_to', models.PositiveIntegerField()),
                ('status', models.PositiveIntegerField()),
            ],
        ),
    ]
