# Generated by Django 2.1.5 on 2020-06-12 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0015_rollback_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rollback_reports',
            name='status',
        ),
    ]
