# Generated by Django 3.1.3 on 2020-12-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0016_remove_rollback_reports_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='rate_btc',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='rate_usd',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
