# Generated by Django 3.1.3 on 2020-12-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0017_auto_20201210_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Max_privacy_withdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
