# Generated by Django 3.1.3 on 2020-12-10 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0019_swap_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swap_stats',
            name='bch',
        ),
    ]
