# Generated by Django 3.1.3 on 2020-12-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0021_auto_20201221_0246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swaps_daily_stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swap_amount', models.CharField(max_length=8)),
                ('swap_currency', models.CharField(max_length=8)),
                ('tx_id', models.CharField(max_length=40, unique=True)),
            ],
        ),
    ]
