# Generated by Django 3.1.3 on 2021-01-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0022_swaps_daily_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='swap_stats',
            name='dai',
            field=models.CharField(default='0', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='swap_stats',
            name='eth',
            field=models.CharField(default='0', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='swap_stats',
            name='usdt',
            field=models.CharField(default='0', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='swap_stats',
            name='wbtc',
            field=models.CharField(default='0', max_length=16),
            preserve_default=False,
        ),
    ]
