# Generated by Django 3.2.15 on 2022-08-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract_calls',
            name='imethod',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
