version: "3.8"

services:
  beam-explorer-mongo:
    image: mongo:6.0.3
    command: mongod --port 27018
    container_name: beam-explorer-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_USER
      - MONGO_PASSWORD
      - MONGO_DB_NAME
    restart: always
  redis-service:
    image: redis:alpine
    command: --port 6380
    expose:
      - "6380"
    restart: always
  server:
    image: server
    container_name: server
    build:
      context: .
      dockerfile: dockerfile-backend
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '4000:4000'
    env_file:
      - .env
    depends_on:
      - beam-explorer-mongo
      - redis-service
volumes:
  dev-mongo-data:
  dev-mongo-conf:
  data:
    driver: local
    driver_opts:
      type: none
      device: /data
      o: bind
